[package]
name = "spin-hello-world"
authors = ["Shota Nakagawa <g21210368a@edu.teu.ac.jp>"]
description = "A simple Spin HTTP component in Rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
# Useful crate to handle errors.
anyhow = "1"
# Crate to simplify working with bytes.
bytes = "1"
chrono = "0.4.19"
cookie = { version = "0.16.0", features = ["percent-encode"] }
# General-purpose crate with common HTTP types.
http = "0.2"
# The Spin SDK.
spin-sdk = { git = "https://github.com/fermyon/spin", tag = "v0.3.0" }
ulid = "0.6.0"
# Crate that generates Rust Wasm bindings from a WebAssembly interface.
wit-bindgen-rust = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "e9c7c0a3405845cecd3fe06f3c20ab413302fc73" }

[workspace]
